# Generated by Django 4.1.1 on 2022-11-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batches',
            old_name='Course',
            new_name='course',
        ),
        migrations.AlterField(
            model_name='students',
            name='resume',
            field=models.FileField(null=True, upload_to='images'),
        ),
    ]
