# Generated by Django 4.1.1 on 2022-11-24 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_course_batches_course_alter_students_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.course'),
        ),
    ]
